Edge support
jianweichuah/miniyoutube pull request #11
Opened 2016-10-03 21:53 UTC by japborst

As Edge and Chrome share the same API, porting was relatively easy. `chrome` becomes `browser` and `storage.sync` can be replaced with `storage.local` as getters and setters work identical.

Included some additional improvements by moving the storage logic to one place.

Tested in both Edge and Chrome, both latest version. Edge requires an additional entry in the manifest, which Chrome warns about but does not break. Might require separate manifest files, but loading in Chrome went just fine. Not sure if that is the case when publishing in the Chrome web store?

Any feedback is appreciated.

2016-10-08 16:38 UTC, jianweichuah commented
Hey Jelmer, thanks for the pull request and sorry for the delayed response as I have been busy at work recently. I'd like to do some testing on both Chrome and Edge first before merging. I'll provide an update once it's done. Thanks for contributing!

2016-10-08 22:09 UTC, japborst commented
No worries. Thanks for the update. 

More than logical that you want to test it first. Let me know if you find some undesired behaviour.

2016-10-13 13:27 UTC, jianweichuah commented on popup.js
> +        browser.runtime.sendMessage({"get_activation_status": true}, function(response) {
Need to add:

```
// Try if Edge browser object exists, else default to chrome
var browser = self.browser;
if (typeof browser === "undefined") {
    browser = self.chrome;
}
```

above for the pop up to work.

2016-10-13 13:29 UTC, jianweichuah requested changes
There were warnings when trying to install this extension:
Unrecognized manifest key 'minimum_edge_version'.

I'm afraid the warning might be confusing to the users. Should we have a separate manifest for Chrome and Edge?

2016-10-14 08:24 UTC, japborst commented on popup.js
> +        browser.runtime.sendMessage({"get_activation_status": true}, function(response) {
Overlooked this one. Thanks!

2016-10-14 09:20 UTC, japborst commented
Separated the manifests to be sure. So no warnings should be expected. Included build script for both chrome and tidied it a little bit in the process.

2016-10-21 13:34 UTC, jianweichuah approved these changes
Looks good!

2016-10-21 13:35 UTC, merged